#!/usr/bin/env bash
#
#SBATCH -J trimSRA # A single job name for the array
#SBATCH --ntasks-per-node=10 # one core
#SBATCH -N 1 # on one node
#SBATCH -t 0-10:00 # 10 hours
#SBATCH --mem 100G
#SBATCH -o /scratch/gpk3qr/erroroutputs/down.%A_%a.out # Standard output
#SBATCH -e /scratch/gpk3qr/erroroutputs/down.%A_%a.err # Standard error
#SBATCH -p standard
#SBATCH --account berglandlab
#SBATCH --array=0-164%10   # Adjust the range based on the number of folders
#mv /scratch/rjp5nc/UK2022_2024/allshortreads/01.RawData/SR* /scratch/rjp5nc/UK2022_2024/allshortreads/01.RawData/SRR/
module load trimmomatic
module load pear

PARENT_DIR="/scratch/gpk3qr/compBio/fastq"
# Get list of all folders
FOLDERS=($(ls -d ${PARENT_DIR}/*/))
FOLDERS=("${FOLDERS[@]:2}")
# Array of folder paths
# Select the folder based on the job array index
FOLDER="${FOLDERS[$SLURM_ARRAY_TASK_ID - 1]}"
if [ -z "$FOLDER" ]; then
  echo "No folder found for task ID $SLURM_ARRAY_TASK_ID"
  exit 1
fi
echo "Total folders found: ${#FOLDERS[@]}"
# Extract folder name
FOLDER_NAME=$(basename "$FOLDER")
# Change to the working directory
cd "$FOLDER" || exit 1
# Check if fastq.gz files exist
if ls *.fastq 1> /dev/null 2>&1; then
    echo "Processing $FOLDER_NAME"
    # Run Trimmomatic
    trimmomatic PE -threads 10 \
        ${FOLDER_NAME}_1.fastq \
        ${FOLDER_NAME}_2.fastq \
        ${FOLDER_NAME}_1.P.trimm.fastq \
        ${FOLDER_NAME}_1.U.trimm.fastq \
        ${FOLDER_NAME}_2.P.trimm.fastq \
        ${FOLDER_NAME}_2.U.trimm.fastq \
        ILLUMINACLIP:/home/gpk3qr/TruSeq3-PE.fa:2:30:10:8:true
    # Run PEAR to merge overlapping reads
    pear -f ${FOLDER_NAME}_1.P.trimm.fastq \
         -r ${FOLDER_NAME}_2.P.trimm.fastq \
         -o ${FOLDER_NAME} \
         -j 10
else
    echo "Warning: No fastq files in $FOLDER_NAME"
fi